ooad-grupa3-tim11/Models/Room.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ooad_grupa3_tim11.Models
{

   
    public class Room
    {
        [Key]
        public int RoomId { get; set; }
        public AccommodationEnum AccommodationType { get; set; }
        public int HotelId { get; set; }
        [ForeignKey("HotelId")]
        public Hotel Hotel { get; set; }
        public bool BestOffer { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
        public int Price { get; set; }


        public Room()
        {
        }

       
        public Room(int roomId, AccommodationEnum accommodationType, int hotelId, Hotel hotel, bool bestOffer, string description, string picture, int price)
        {
            RoomId = roomId;
           
            AccommodationType = accommodationType;
            HotelId = hotelId;
            Hotel = hotel;
            BestOffer = bestOffer;
            Description = description;
            Picture = picture;
            Price = price;
        }
    }
}

ooad-grupa3-tim11/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ooad_grupa3_tim11.Data;
using ooad_grupa3_tim11.Models;

namespace ooad_grupa3_tim11.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;


        public ReservationsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Reservations
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Challenge();
            }

            var reservations = _context.Reservation
                .Where(r => r.RegisteredUserId == user.Id)
                .Include(r => r.Room)
                .ToList();
            return View(reservations);

            var applicationDbContext = _context.Reservation.Include(r => r.Room);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .Include(r => r.Room)
                .FirstOrDefaultAsync(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations/Create
        public IActionResult Create(int? roomId)
        {
            Room selectedRoom = null;

            if (roomId.HasValue)
            {
                selectedRoom = _context.Room
                    .Include(r => r.Hotel)
                    .FirstOrDefault(r => r.RoomId == roomId.Value);
            }

            ViewBag.SelectedRoom = selectedRoom;
            ViewData["RoomId"] = new SelectList(_context.Room, "RoomId", "RoomId");
            return View(new Reservation { RoomId = roomId.GetValueOrDefault() });
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReservationId,StartDate,EndDate,Price,RoomId,RegisteredUserId")] Reservation reservation, string fullName)
        {
            var userEmail = User.Identity.Name;
            if (userEmail == null)
            {
                return Unauthorized();
            }

            var registeredUser = await _context.RegisteredUser.FirstOrDefaultAsync(u => u.Email == userEmail);

         
            reservation.RegisteredUser = registeredUser;

            //if (ModelState.IsValid){}
            var selectedRoom1 = await _context.Room
        .FirstOrDefaultAsync(r => r.RoomId == reservation.RoomId);

            if (selectedRoom1 == null)
            {
                // Handle the case where the room is not found
                return NotFound();
            }

            // Set the reservation price to the price of the selected room
            reservation.Price = selectedRoom1.Price; // Assuming Price is a property of Room

            _context.Reservation.Add(reservation);
            await _context.SaveChangesAsync();

            //TempData["Message"] = $"Reservation created successfully: {userEmail} {fullName} {reservation.RoomId}";
            return RedirectToAction(nameof(Index));


            var selectedRoom = _context.Room
                .Include(r => r.Hotel)
                .FirstOrDefault(r => r.RoomId == reservation.RoomId);

            ViewBag.SelectedRoom = selectedRoom;
            ViewData["RoomId"] = new SelectList(_context.Room, "RoomId", "RoomId", reservation.RoomId);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            ViewData["RoomId"] = new SelectList(_context.Room, "RoomId", "RoomId", reservation.RoomId);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReservationId,StartDate,EndDate,Price,RoomId")] Reservation reservation)
        {
            if (id != reservation.ReservationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(reservation.ReservationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoomId"] = new SelectList(_context.Room, "RoomId", "RoomId", reservation.RoomId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .Include(r => r.Room)
                .FirstOrDefaultAsync(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservation.FindAsync(id);
            if (reservation != null)
            {
                _context.Reservation.Remove(reservation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservation.Any(e => e.ReservationId == id);
        }
    }
}

ooad-grupa3-tim11/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ooad_grupa3_tim11.Data;
using ooad_grupa3_tim11.Models;
using System.Diagnostics;
using Newtonsoft.Json;


namespace ooad_grupa3_tim11.Controllers
{
    public class RoomsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RoomsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Rooms
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Room.Include(r => r.Hotel);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room
                .Include(r => r.Hotel)
                .FirstOrDefaultAsync(m => m.RoomId == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            ViewData["HotelId"] = new SelectList(_context.Hotel, "HotelId", "HotelId");
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       
        public async Task<IActionResult> Create([Bind("RoomId,AccommodationType,HotelId,BestOffer,Description,Picture,Price")] Room room)
        {
            var hotel = await _context.Hotel
            .Include(h => h.Location) // Include the Location related to the Hotel
            .FirstOrDefaultAsync(h => h.HotelId == room.HotelId);
            if (hotel == null)
            {
                ModelState.AddModelError("HotelId", "Invalid HotelId");
                return View(room);
            }

            // Poveži hotel sa sobom
            room.Hotel = hotel;

            Debug.WriteLine($"New Room created: {JsonConvert.SerializeObject(room)}");
            if (true)
                {
                    _context.Add(room);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }            
               
            ViewData["HotelId"] = new SelectList(_context.Hotel, "HotelId", "HotelId", room.HotelId);

            foreach (var state in ModelState)
            {
                foreach (var error in state.Value.Errors)
                {
                    Debug.WriteLine($"Property: {state.Key} Error: {error.ErrorMessage}");
                }
            }
            return View(room);
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            ViewData["HotelId"] = new SelectList(_context.Hotel, "HotelId", "HotelId", room.HotelId);
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoomId,AccommodationType,HotelId,BestOffer,Description,Picture,Price")] Room room)
        {
            if (id != room.RoomId)
            {
                return NotFound();
            }
            var hotel = await _context.Hotel
            .Include(h => h.Location) // Include the Location related to the Hotel
            .FirstOrDefaultAsync(h => h.HotelId == room.HotelId);
            if (hotel == null)
            {
                ModelState.AddModelError("HotelId", "Invalid HotelId");
                return View(room);
            }

            // Poveži hotel sa sobom
            room.Hotel = hotel;

            if (true)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.RoomId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HotelId"] = new SelectList(_context.Hotel, "HotelId", "HotelId", room.HotelId);
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room
                .Include(r => r.Hotel)
                .FirstOrDefaultAsync(m => m.RoomId == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Room.FindAsync(id);
            if (room != null)
            {
                _context.Room.Remove(room);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Room.Any(e => e.RoomId == id);
        }

        public async Task<IActionResult> HomePage(string searchString, int? cityId, decimal? minPrice, decimal? maxPrice, AccommodationEnum? accommodationType)
        {
            var rooms = _context.Room.Include(r => r.Hotel).AsQueryable();

            // Apply city filter
            if (cityId.HasValue)
            {
                rooms = rooms.Where(r => r.Hotel.LocationId == cityId);
            }

            // Apply price range filter
            if (minPrice.HasValue)
            {
                rooms = rooms.Where(r => r.Price >= minPrice);
            }

            if (maxPrice.HasValue)
            {
                rooms = rooms.Where(r => r.Price <= maxPrice);
            }

            // Apply accommodation type filter
            if (accommodationType.HasValue)
            {
                rooms = rooms.Where(r => r.AccommodationType == accommodationType);
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                rooms = rooms.Where(r => r.Description.Contains(searchString) || r.Hotel.Name.Contains(searchString));
            }

            var viewModel = new HomeFiltersViewModel
        {
            Cities = await _context.Location.ToListAsync(), // Assuming Location is your model for cities
            MinPrice = await _context.Room.MinAsync(r => r.Price),
            MaxPrice = await _context.Room.MaxAsync(r => r.Price)
        };

            return View((viewModel, await rooms.ToListAsync()));
        }
    }
}

ooad-grupa3-tim11/Views/Rooms/Create.cshtml
@model ooad_grupa3_tim11.Models.Room

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccommodationType" class="control-label"></label>
                <select asp-for="AccommodationType" class="form-control">
                    @foreach (var value in Enum.GetValues(typeof(AccommodationEnum)))
                    {
                        <option value="@value">@value</option>
                    }
                </select>
                <span asp-validation-for="AccommodationType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelId" class="control-label"></label>
                <select asp-for="HotelId" class="form-control" asp-items="ViewBag.HotelId"></select>
                <span asp-validation-for="HotelId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="BestOffer" /> @Html.DisplayNameFor(model => model.BestOffer)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ooad-grupa3-tim11/Views/Rooms/Delete.cshtml
@model ooad_grupa3_tim11.Models.Room

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccommodationType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccommodationType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hotel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hotel.HotelId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BestOffer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BestOffer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RoomId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ooad-grupa3-tim11/Views/Rooms/Details.cshtml
@model ooad_grupa3_tim11.Models.Room

@{
    ViewData["Title"] = "Room Details";
}

<div class="card mb-4">
    <div class="card-header">
        <h2>Room Details</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <img src="@Model.Picture" alt="Room Picture" class="img-fluid rounded mb-3" />
            </div>
            <div class="col-md-8">
                <dl class="row">
                    <dt class="col-sm-4">@Html.DisplayNameFor(model => model.AccommodationType)</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.AccommodationType)</dd>

                    <dt class="col-sm-4">@Html.DisplayNameFor(model => model.Hotel)</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.Hotel.Name)</dd>

                    <dt class="col-sm-4">@Html.DisplayNameFor(model => model.BestOffer)</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.BestOffer)</dd>

                    <dt class="col-sm-4">@Html.DisplayNameFor(model => model.Description)</dt>
                    <dd class="col-sm-8">@Html.DisplayFor(model => model.Description)</dd>

                    <dt class="col-sm-4">@Html.DisplayNameFor(model => model.Price)</dt>
                    <dd class="col-sm-8">@Model.Price $</dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="card-footer text-right">
        <a asp-action="Edit" asp-route-id="@Model?.RoomId" class="btn btn-primary">Edit</a>
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

ooad-grupa3-tim11/Views/Rooms/Edit.cshtml
@model ooad_grupa3_tim11.Models.Room

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RoomId" />
            <div class="form-group">
                <select asp-for="AccommodationType" class="form-control">
                    @foreach (var value in Enum.GetValues(typeof(AccommodationEnum)))
                    {
                        <option value="@value">@value</option>
                    }
                </select>
                <span asp-validation-for="AccommodationType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelId" class="control-label"></label>
                <select asp-for="HotelId" class="form-control" asp-items="ViewBag.HotelId"></select>
                <span asp-validation-for="HotelId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="BestOffer" /> @Html.DisplayNameFor(model => model.BestOffer)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ooad-grupa3-tim11/Views/Rooms/HomePage.cshtml
<div class="text-center">
    <h1 class="display-4">Rooms</h1>
</div>

<form method="get" action="@Url.Action("HomePage")">
    <div class="form-group">
        <input type="text" name="searchString" value="@Context.Request.Query["searchString"]" class="form-control" placeholder="Search for rooms or hotels" />
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>

<div class="container mt-4">
    <!-- Filter form -->
    <form method="get" action="@Url.Action("HomePage")">
        <div class="row">
            <!-- City filter -->
            <div class="col-md-4 mb-3">
                <label for="cityId">City</label>
                <select class="form-control" id="cityId" name="cityId">
                    <option value="">All Cities</option>
                    @foreach (var city in Model.Item1.Cities)
                    {
                        <option value="@city.LocationId">@city.Name</option>
                    }
                </select>
            </div>

            <!-- Price range filter -->
            <div class="col-md-4 mb-3">
                <label for="minPrice">Min Price</label>
                <input type="number" class="form-control" id="minPrice" name="minPrice" min="@Model.Item1.MinPrice" value="@Model.Item1.MinPrice" />
            </div>
            <div class="col-md-4 mb-3">
                <label for="maxPrice">Max Price</label>
                <input type="number" class="form-control" id="maxPrice" name="maxPrice" min="@Model.Item1.MinPrice" max="@Model.Item1.MaxPrice" value="@Model.Item1.MaxPrice" />
            </div>

            <!-- Accommodation type filter -->
            <div class="col-md-4 mb-3">
                <label for="accommodationType">Accommodation Type</label>
                <select class="form-control" id="accommodationType" name="accommodationType">
                    <option value="">All Accommodation Types</option>
                    @foreach (AccommodationEnum type in Enum.GetValues(typeof(AccommodationEnum)))
                    {
                        <option value="@type">@type</option>
                    }
                </select>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Apply Filters</button>
    </form>
</div>

<div class="row">
    @foreach (var item in Model.Item2)
    {
        <div class="col-md-4 mb-4">
            <div class="card">
                <img src="@item.Picture" class="card-img-top" alt="Room Picture">
                <div class="card-body">
                    <h5 class="card-title">@item.Hotel.Name</h5>
                    <p class="card-text">Accommodation Type: @item.AccommodationType</p>
                    <a href="@Url.Action("Details", "Rooms", new { id = item.RoomId })" class="btn btn-primary">Details</a>
                    @if (User.IsInRole("Administrator") || User.IsInRole("Manager") || User.IsInRole("Korisnik")){
                    <a href="@Url.Action("Create", "Reservations", new { roomId = item.RoomId })" class="btn btn-success">Make Reservation</a>
                    }
                </div>
            </div>
        </div>
    }
</div>

ooad-grupa3-tim11/Views/Rooms/Index.cshtml
@model IEnumerable<ooad_grupa3_tim11.Models.Room>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Admin</h1>
 
</div>

<div>
    <h2>Rooms</h2>
    <p>
        <a asp-action="Create" class="btn btn-primary">Create New</a>
    </p>
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>@Html.DisplayNameFor(model => model.AccommodationType)</th>
                <th>@Html.DisplayNameFor(model => model.Hotel.Name)</th>
                <th>@Html.DisplayNameFor(model => model.BestOffer)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th>@Html.DisplayNameFor(model => model.Picture)</th>
                <th>@Html.DisplayNameFor(model => model.Price)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.AccommodationType)</td>
                    <td>@Html.DisplayFor(modelItem => item.Hotel.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.BestOffer)</td>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>
                    <td>
                        <img src="@item.Picture" alt="Room Picture" style="max-width: 200px; height: auto;" />
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Price)</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.RoomId" class="btn btn-secondary">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.RoomId" class="btn btn-info">Details</a>
                        <a asp-action="Delete" asp-route-id="@item.RoomId" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>